name: "Setup build environment"
description: "Setup python, ninja-build etc."

# Make top-level permissions on GITHUB_TOKEN more restrictive
permissions:
  contents: read

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.11'

    - name: Install prerequisites (Linux)
      run: sudo apt-get install --yes ninja-build
      shell: bash
